export { polymorphic } from './config'
export { toPolymorphic } from './polymorphic'
// export { factory } from './factory'
export type { ComponentSpec, FactorySpec } from './factory'
export type { PolymorphicSpecs } from './config'
export type { SpecStructure } from './structure'
